enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube-Morphe]
rv-brand = "Morphe"
app-name = "YouTube"
version = "auto"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
included-patches = "'Change package name'"
excluded-patches = "'Enable debugging'"
patcher-args = "-OpackageName=yt.morphe.noname.exe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Morphe]
rv-brand = "Morphe"
app-name = "Music"
module-prop-name = "ytm-morphe"
arch = "both"
version = "auto"
build-mode = "module"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
excluded-patches = "'Enable debugging'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
