logging-to-file = true
enable-magisk-update = false
build-mindetach-module = false

# extended
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"

[YouTube]
build-mode = "apk"
excluded-patches = "custom-branding-icon-afn-red custom-branding-name custom-seekbar-color disable-haptic-feedback hide-cast-button hide-channel-watermark"
included-patches = "custom-branding-icon-afn-blue"
version = "auto"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music-arm64]
build-mode = "apk"
app-name = "Music"
excluded-patches = "custom-branding-music-afn-red"
included-patches = "custom-branding-music-afn-blue"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
